### ISSUE TITLE
How to handle not listed user apps?

### ISSUE THREAD

**Issue by philippgaertner** [samapriya/ee-appshot#1]
How to deal with the case when a person does not appear in the git list, but an app exists (e.g. user: corneliussenf; https://corneliussenf.users.earthengine.app/view/european-disturbance-map)

**Comment by samapriya** [comment]
So these would have to be added or shared by users manually. Then the source code could be fetched and added onto it. 

We can create a GitHub template for people to submit link to unlisted apps and we can add them. Same as what I am doing with data, people are submitting data requests using a template right now

**Comment by samapriya** [comment]
I added or tried to fetch all apps :) that were tweeted about in 2020-2021 so now the list and the app zip contains the app you mentioned including additional apps from the time period. I am closing this issue but I will try to work on the app template and submission idea for users to submit apps by themselves

**Comment by philippgaertner** [comment]
Awesome, well done!

**Comment by philippgaertner** [comment]
Hi Sam, are there any news about the template idea? Just came across an app which is not listed and remembered the issue. 
https://tirthankar25.users.earthengine.app/view/konturpop

**Comment by samapriya** [comment]
Thanks for the reminder I will create one by next week 🙂
